import io
import unittest
from pathlib import Path
from unittest.mock import patch

import numpy as np
import numpy.testing as npt
from astropy.time import Time

from src.ephemeris import _parse_row, parse_ephemeris_from_csv


class TestEphemeris(unittest.TestCase):
    def test_parse_row_returns_ephemeris_point(self):
        row = [
            "2459573.5",
            "A.D. 2021-Dec-25 00:00:00.0000",
            "1.0",
            "2.0",
            "3.0",
            "0.1",
            "0.2",
            "0.3",
        ]

        point = _parse_row(row)

        self.assertIsInstance(point.time, Time)
        npt.assert_array_equal(point.pos, np.array([1.0, 2.0, 3.0]))
        npt.assert_array_equal(point.vel, np.array([0.1, 0.2, 0.3]))

    def test_parse_row_raises_value_error_for_invalid_data(self):
        row = [
            "2459573.5",
            "A.D. 2021-Dec-25 00:00:00.0000",
            "1.0",
            "not-a-number",
            "3.0",
            "0.1",
            "0.2",
            "0.3",
        ]

        with self.assertRaisesRegex(ValueError, "Error parsing row"):
            _parse_row(row)

    def test_open_ephemeris_csv_parses_rows_between_markers(self):
        csv_content = "\n".join(
            [
                "metadata line",
                "generated by some tool",
                "$$SOE",
                "2459573.5,A.D. 2021-Dec-25 00:00:00.0000,1.0,2.0,3.0,0.1,0.2,0.3",
                "2459574.5,A.D. 2021-Dec-26 00:00:00.0000,4.0,5.0,6.0,0.4,0.5,0.6",
                "$$EOE",
                "trailing line",
            ]
        )

        with patch(
            "src.ephemeris.open", return_value=io.StringIO(csv_content), create=True
        ):
            eph = parse_ephemeris_from_csv(Path("ignored_argument.csv"))

        self.assertEqual(eph.positions.shape, (2, 3))
        self.assertEqual(eph.velocities.shape, (2, 3))

        npt.assert_array_equal(
            eph.positions, np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
        )
        npt.assert_array_equal(
            eph.velocities, np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
        )


if __name__ == "__main__":
    unittest.main()
