"""
This type stub file was generated by pyright.
"""

from pkg_resources import DistributionNotFound, get_distribution
from .gs_version import glowscript_version
from ._notebook_helpers import __is_spyder, _warn_if_spyder_settings_wrong
from .vpython import canvas
from .shapespaths import *
from ._vector_import_helper import *
from .rate_control import rate
from math import *
from numpy import arange
from random import random

__version__ = ...
__gs_version__ = ...
scene = ...
if __is_spyder():
    ...
