"""
This type stub file was generated by pyright.
"""

import platform
from .vector import *
from .cyvector import *

if platform.python_implementation() == 'PyPy':
    ...
else:
    v = ...
vec = ...
