"""
This type stub file was generated by pyright.
"""

def glowscript_version(): # -> str | Any:
    """
    Extract the Glowscript version from the javascript in the data directory.
    """
    ...

