"""
This type stub file was generated by pyright.
"""

from ._notebook_helpers import _isnotebook

_clock = ...
_tick = ...
if _isnotebook:
    ws_queue = ...
MIN_RENDERS = ...
MAX_RENDERS = ...
INTERACT_PERIOD = ...
USER_FRACTION = ...
class simulateDelay:
    """
    Simulate rendering/compute times.. with an average value of delayAvg with
    a variance of something like delaySigma**2.
    """
    def __init__(self, delayAvg=..., delaySigma=...) -> None:
        ...
    
    def __call__(self): # -> None:
        ...
    


class RateKeeper:
    def __init__(self, interactPeriod=..., interactFunc=...) -> None:
        ...
    
    def initialize(self): # -> None:
        ...
    
    def callInteract(self): # -> None:
        ...
    
    def distributeRenders(self, M, N): # -> None:
        ...
    
    def buildStrategy(self, rate): # -> None:
        ...
    
    def __call__(self, maxRate=...): # -> None:
        ...
    


def message_send_wrapper(): # -> Callable[..., None]:
    """
    The only purpose of this function is delay import of baseObj to eliminate
    what would otherwise be a circular import. __init__ imports rate, and vpython imports rate,
    and this cannot also import vpython at the same time.
    """
    ...

class _RateKeeper2(RateKeeper):
    def __init__(self, interactPeriod=..., interactFunc=...) -> None:
        ...
    
    def sendtofrontend(self): # -> None:
        ...
    
    def __call__(self, N): # -> None:
        ...
    


rate = ...
