"""
This type stub file was generated by pyright.
"""

__all__ = ['adjust_axis', 'adjust_up', 'comp', 'cross', 'diff_angle', 'dot', 'hat', 'mag', 'mag2', 'norm', 'object_rotate', 'proj', 'rotate', 'vector']
class vector:
    'vector class'
    @staticmethod
    def random(): # -> vector:
        ...
    
    def __init__(self, *args) -> None:
        ...
    
    def ignore(self): # -> None:
        ...
    
    @property
    def value(self): # -> list[float | Any]:
        ...
    
    @value.setter
    def value(self, other): # -> None:
        ...
    
    def __neg__(self): # -> vector:
        ...
    
    def __pos__(self): # -> Self:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __add__(self, other): # -> vector | NotImplementedType:
        ...
    
    def __sub__(self, other): # -> vector | NotImplementedType:
        ...
    
    def __truediv__(self, other): # -> vector | NotImplementedType:
        ...
    
    def __mul__(self, other): # -> vector | NotImplementedType:
        ...
    
    def __rmul__(self, other): # -> vector | NotImplementedType:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    @property
    def x(self): # -> float:
        ...
    
    @x.setter
    def x(self, value): # -> None:
        ...
    
    @property
    def y(self): # -> float:
        ...
    
    @y.setter
    def y(self, value): # -> None:
        ...
    
    @property
    def z(self): # -> float:
        ...
    
    @z.setter
    def z(self, value): # -> None:
        ...
    
    @property
    def mag(self): # -> float:
        ...
    
    @mag.setter
    def mag(self, value): # -> None:
        ...
    
    @property
    def mag2(self): # -> float:
        ...
    
    @mag2.setter
    def mag2(self, value): # -> None:
        ...
    
    @property
    def hat(self): # -> vector | NotImplementedType:
        ...
    
    @hat.setter
    def hat(self, value): # -> None:
        ...
    
    def norm(self): # -> vector | NotImplementedType:
        ...
    
    def dot(self, other):
        ...
    
    def cross(self, other): # -> vector:
        ...
    
    def proj(self, other):
        ...
    
    def equals(self, other):
        ...
    
    def comp(self, other):
        ...
    
    def diff_angle(self, other): # -> float | Literal[0]:
        ...
    
    def rotate(self, angle=..., axis=...): # -> vector:
        ...
    
    def rotate_in_place(self, angle=..., axis=...): # -> None:
        ...
    


def object_rotate(objaxis, objup, angle, axis): # -> None:
    ...

def mag(A):
    ...

def mag2(A):
    ...

def norm(A):
    ...

def hat(A):
    ...

def dot(A, B):
    ...

def cross(A, B):
    ...

def proj(A, B):
    ...

def comp(A, B):
    ...

def diff_angle(A, B):
    ...

def rotate(A, angle=..., axis=...):
    ...

def adjust_up(oldaxis, newaxis, up, save_oldaxis): # -> None:
    ...

def adjust_axis(oldup, newup, axis, save_oldup): # -> None:
    ...

