"""
This type stub file was generated by pyright.
"""

import platform
import sys
from ._vector_import_helper import dot

clock = ...
def sign(x): # -> Literal[1, -1, 0]:
    ...

def Exit(): # -> None:
    ...

if platform.system() == 'Windows':
    ...
__all__ = ['Camera', 'GlowWidget', 'version', 'GSversion', 'Mouse', 'arrow', 'attach_arrow', 'attach_light', 'attach_trail', 'baseObj', 'box', 'bumpmaps', 'button', 'canvas', 'checkbox', 'clock', 'color', 'combin', 'compound', 'cone', 'controls', 'curve', 'curveMethods', 'cylinder', 'distant_light', 'ellipsoid', 'event_return', 'extrusion', 'faces', 'frame', 'gcurve', 'gdots', 'ghbars', 'gobj', 'graph', 'gvbars', 'helix', 'label', 'local_light', 'menu', 'meta_canvas', 'points', 'pyramid', 'quad', 'radio', 'ring', 'set_browser', 'simple_sphere', 'sleep', 'slider', 'sphere', 'standardAttributes', 'text', 'textures', 'triangle', 'vertex', 'wtext', 'winput', 'keysdown', 'sign']
version = ...
GSversion = ...
keysdownlist = ...
__attrs = ...
__attrsb = ...
__methods = ...
__vecattrs = ...
__textattrs = ...
if sys.version > '3':
    long = int
def list_to_vec(L): # -> vector:
    ...

class baseObj:
    glow = ...
    objCnt = ...
    sent = ...
    _view_constructed = ...
    _canvas_constructing = ...
    updates = ...
    object_registry = ...
    attach_arrows = ...
    attach_trails = ...
    follow_objects = ...
    attrs = ...
    @classmethod
    def initialize(cls): # -> None:
        ...
    
    @classmethod
    def empty(cls): # -> bool:
        ...
    
    @classmethod
    def handle_attach(cls): # -> None:
        ...
    
    def __init__(self, **kwargs) -> None:
        ...
    
    def delete(self): # -> None:
        ...
    
    def appendcmd(self, cmd): # -> None:
        ...
    
    def addmethod(self, method, data): # -> None:
        ...
    
    def addattr(self, attr): # -> None:
        ...
    
    @classmethod
    def package(cls, objdata): # -> dict[Any, Any]:
        ...
    
    @classmethod
    def trigger(cls): # -> None:
        ...
    
    @classmethod
    def incrObjCnt(cls): # -> None:
        ...
    
    @classmethod
    def decrObjCnt(cls): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    


class GlowWidget:
    def __init__(self, wsport=..., wsuri=...) -> None:
        ...
    
    def handle_msg(self, msg): # -> None:
        ...
    
    def handle_close(self, data): # -> None:
        ...
    


class color:
    black = ...
    white = ...
    red = ...
    green = ...
    blue = ...
    yellow = ...
    cyan = ...
    magenta = ...
    orange = ...
    purple = ...
    @classmethod
    def gray(cls, luminance): # -> vector:
        ...
    
    @classmethod
    def rgb_to_hsv(cls, v): # -> vector:
        ...
    
    @classmethod
    def hsv_to_rgb(cls, v): # -> vector:
        ...
    
    @classmethod
    def rgb_to_grayscale(cls, v): # -> vector:
        ...
    


class textures:
    flower = ...
    granite = ...
    gravel = ...
    earth = ...
    metal = ...
    rock = ...
    rough = ...
    rug = ...
    stones = ...
    stucco = ...
    wood = ...
    wood_old = ...


class bumpmaps:
    gravel = ...
    rock = ...
    stones = ...
    stucco = ...
    wood_old = ...


class standardAttributes(baseObj):
    attrLists = ...
    def setup(self, args):
        ...
    
    @property
    def pos(self): # -> vector:
        ...
    
    @pos.setter
    def pos(self, value): # -> None:
        ...
    
    @property
    def up(self): # -> vector:
        ...
    
    @up.setter
    def up(self, value): # -> None:
        ...
    
    @property
    def axis(self): # -> vector | NotImplementedType | Any:
        ...
    
    @axis.setter
    def axis(self, value): # -> None:
        ...
    
    @property
    def size(self):
        ...
    
    @size.setter
    def size(self, value): # -> None:
        ...
    
    @property
    def length(self):
        ...
    
    @length.setter
    def length(self, value): # -> None:
        ...
    
    @property
    def height(self):
        ...
    
    @height.setter
    def height(self, value): # -> None:
        ...
    
    @property
    def width(self):
        ...
    
    @width.setter
    def width(self, value): # -> None:
        ...
    
    @property
    def color(self): # -> vector | tuple[Any, float | Any, float | Any] | tuple[float | Any, Any, float | Any] | tuple[float | Any, float | Any, Any]:
        ...
    
    @color.setter
    def color(self, value): # -> None:
        ...
    
    @property
    def red(self): # -> float:
        ...
    
    @red.setter
    def red(self, value): # -> None:
        ...
    
    @property
    def green(self): # -> float:
        ...
    
    @green.setter
    def green(self, value): # -> None:
        ...
    
    @property
    def blue(self): # -> float:
        ...
    
    @blue.setter
    def blue(self, value): # -> None:
        ...
    
    @property
    def visible(self): # -> bool:
        ...
    
    @visible.setter
    def visible(self, value): # -> None:
        ...
    
    @property
    def pickable(self): # -> bool:
        ...
    
    @pickable.setter
    def pickable(self, value): # -> None:
        ...
    
    @property
    def canvas(self): # -> None:
        ...
    
    @canvas.setter
    def canvas(self, value): # -> None:
        ...
    
    @property
    def opacity(self): # -> float:
        ...
    
    @opacity.setter
    def opacity(self, value): # -> None:
        ...
    
    @property
    def emissive(self): # -> bool:
        ...
    
    @emissive.setter
    def emissive(self, value): # -> None:
        ...
    
    @property
    def texture(self): # -> None:
        ...
    
    @texture.setter
    def texture(self, value): # -> None:
        ...
    
    @property
    def shininess(self): # -> float:
        ...
    
    @shininess.setter
    def shininess(self, value): # -> None:
        ...
    
    @property
    def make_trail(self): # -> bool:
        ...
    
    @make_trail.setter
    def make_trail(self, value): # -> None:
        ...
    
    @property
    def trail_type(self): # -> str:
        ...
    
    @trail_type.setter
    def trail_type(self, value): # -> None:
        ...
    
    @property
    def trail_color(self): # -> vector:
        ...
    
    @trail_color.setter
    def trail_color(self, value): # -> None:
        ...
    
    @property
    def interval(self): # -> int:
        ...
    
    @interval.setter
    def interval(self, value): # -> None:
        ...
    
    @property
    def retain(self): # -> int:
        ...
    
    @retain.setter
    def retain(self, value): # -> None:
        ...
    
    @property
    def trail_radius(self): # -> None:
        ...
    
    @trail_radius.setter
    def trail_radius(self, value): # -> None:
        ...
    
    @property
    def pps(self):
        ...
    
    @pps.setter
    def pps(self, value): # -> None:
        ...
    
    @property
    def frame(self): # -> None:
        ...
    
    @frame.setter
    def frame(self, value): # -> None:
        ...
    
    def rotate(self, angle=..., axis=..., origin=...): # -> None:
        ...
    
    def bounding_box(self): # -> list[Any]:
        ...
    
    def clear_trail(self): # -> None:
        ...
    
    def clone(self, **args): # -> compound | Self:
        ...
    
    def __del__(self): # -> None:
        ...
    


class box(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    


class sphere(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def radius(self): # -> float:
        ...
    
    @radius.setter
    def radius(self, value): # -> None:
        ...
    
    @property
    def size(self): # -> vector:
        ...
    
    @size.setter
    def size(self, value): # -> None:
        ...
    
    @property
    def axis(self): # -> vector | NotImplementedType | Any:
        ...
    
    @axis.setter
    def axis(self, value): # -> None:
        ...
    


class simple_sphere(sphere):
    def __init__(self, **args) -> None:
        ...
    


class cylinder(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def radius(self):
        ...
    
    @radius.setter
    def radius(self, value): # -> None:
        ...
    


class cone(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def radius(self):
        ...
    
    @radius.setter
    def radius(self, value): # -> None:
        ...
    


class pyramid(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    


class ellipsoid(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def radius(self):
        ...
    
    @radius.setter
    def radius(self, value): # -> None:
        ...
    


class ring(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def thickness(self): # -> float:
        ...
    
    @thickness.setter
    def thickness(self, value): # -> None:
        ...
    
    @property
    def radius(self): # -> float:
        ...
    
    @radius.setter
    def radius(self, value): # -> None:
        ...
    
    @property
    def axis(self): # -> vector:
        ...
    
    @axis.setter
    def axis(self, value): # -> None:
        ...
    
    @property
    def size(self): # -> vector:
        ...
    
    @size.setter
    def size(self, value): # -> None:
        ...
    


class arrow(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def round(self): # -> bool:
        ...
    
    @round.setter
    def round(self, value):
        ...
    
    @property
    def shaftwidth(self): # -> int:
        ...
    
    @shaftwidth.setter
    def shaftwidth(self, value): # -> None:
        ...
    
    @property
    def headwidth(self): # -> int:
        ...
    
    @headwidth.setter
    def headwidth(self, value): # -> None:
        ...
    
    @property
    def headlength(self): # -> int:
        ...
    
    @headlength.setter
    def headlength(self, value): # -> None:
        ...
    
    @property
    def round(self): # -> bool:
        ...
    
    @round.setter
    def round(self, value):
        ...
    
    @property
    def scale(self):
        ...
    
    @scale.setter
    def scale(self, value): # -> None:
        ...
    
    @property
    def shaftwidth(self): # -> int:
        ...
    
    @shaftwidth.setter
    def shaftwidth(self, value): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def start(self): # -> None:
        ...
    


def attach_arrow(o, attr, **args): # -> arrow:
    '''
    The object "o" with a vector attribute "p" will have an arrow attached with options such as "color".
    The length of the arrow will be args.scale*o.p", updated with every render of the scene.
    If one creates a new attachment with "arr = attach_arrow(obj, attr, options)" you
    can later change (for example) its color with "arr.color = ..."
    '''
    ...

def attach_light(o, **args): # -> local_light:
    '''
    The object "o" will have a local_light attached with options "offset" and "color".
    The local_light will constantly be positioned at o.pos plus the offset.
    '''
    ...

class attach_trail(standardAttributes):
    def __init__(self, obj, **args) -> None:
        ...
    
    @property
    def radius(self): # -> int:
        ...
    
    @radius.setter
    def radius(self, value): # -> None:
        ...
    
    @property
    def retain(self): # -> int:
        ...
    
    @retain.setter
    def retain(self, value): # -> None:
        ...
    
    @property
    def pps(self): # -> int:
        ...
    
    @pps.setter
    def pps(self, value): # -> None:
        ...
    
    @property
    def type(self): # -> str:
        ...
    
    @type.setter
    def type(self, value): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def start(self): # -> None:
        ...
    
    def clear(self): # -> None:
        ...
    


class helix(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def thickness(self): # -> float:
        ...
    
    @thickness.setter
    def thickness(self, value): # -> None:
        ...
    
    @property
    def coils(self): # -> int:
        ...
    
    @coils.setter
    def coils(self, value): # -> None:
        ...
    
    @property
    def ccw(self): # -> bool:
        ...
    
    @ccw.setter
    def ccw(self, value): # -> None:
        ...
    
    @property
    def radius(self): # -> float:
        ...
    
    @radius.setter
    def radius(self, value): # -> None:
        ...
    


class compound(standardAttributes):
    compound_idx = ...
    def __init__(self, objList, **args) -> None:
        ...
    
    @property
    def obj_idxs(self): # -> None:
        ...
    
    @property
    def axis(self): # -> vector | NotImplementedType | Any:
        ...
    
    @axis.setter
    def axis(self, value): # -> None:
        ...
    
    @property
    def size(self):
        ...
    
    @size.setter
    def size(self, value): # -> None:
        ...
    
    @property
    def origin(self):
        ...
    
    @origin.setter
    def origin(self, value): # -> None:
        ...
    
    def world_to_compound(self, v):
        ...
    
    def compound_to_world(self, v):
        ...
    


class vertex(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def triangleCount(self): # -> int:
        ...
    
    @triangleCount.setter
    def triangleCount(self, val):
        ...
    
    def decrementTriangleCount(self): # -> None:
        ...
    
    def incrementTriangleCount(self): # -> None:
        ...
    
    @property
    def normal(self): # -> vector:
        ...
    
    @normal.setter
    def normal(self, value): # -> None:
        ...
    
    @property
    def bumpaxis(self): # -> vector:
        ...
    
    @bumpaxis.setter
    def bumpaxis(self, value): # -> None:
        ...
    
    @property
    def texpos(self): # -> vector:
        ...
    
    @texpos.setter
    def texpos(self, value): # -> None:
        ...
    


class triangle(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    @property
    def v0(self): # -> None:
        ...
    
    @v0.setter
    def v0(self, value): # -> None:
        ...
    
    @property
    def v1(self): # -> None:
        ...
    
    @v1.setter
    def v1(self, value): # -> None:
        ...
    
    @property
    def v2(self): # -> None:
        ...
    
    @v2.setter
    def v2(self, value): # -> None:
        ...
    
    @property
    def vs(self): # -> list[Any | None]:
        ...
    
    @vs.setter
    def vs(self, value): # -> None:
        ...
    


class quad(triangle):
    def __init__(self, **args) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    @property
    def v3(self): # -> None:
        ...
    
    @v3.setter
    def v3(self, value): # -> None:
        ...
    
    @property
    def vs(self): # -> list[Any]:
        ...
    
    @vs.setter
    def vs(self, value): # -> None:
        ...
    


class curveMethods(standardAttributes):
    def process_args(self, *args1, **args): # -> list[list[Any]]:
        ...
    
    def parse_pos(self, *vars): # -> list[Any]:
        ...
    
    def append(self, *args1, **args): # -> None:
        ...
    
    @property
    def npoints(self): # -> int:
        ...
    
    @npoints.setter
    def npoints(self, value):
        ...
    
    @property
    def radius(self):
        ...
    
    @radius.setter
    def radius(self, value): # -> None:
        ...
    
    def pop(self, *args): # -> None:
        ...
    
    def point(self, N):
        ...
    
    def clear(self): # -> None:
        ...
    
    def shift(self): # -> None:
        ...
    
    def unshift(self, *args1, **args): # -> None:
        ...
    
    def slice(self, start, end): # -> list[Any]:
        ...
    
    def splice(self, start, howmany, *args1): # -> None:
        ...
    
    def modify(self, N, *arg1, **args): # -> None:
        ...
    
    @property
    def origin(self):
        ...
    
    @origin.setter
    def origin(self, value): # -> None:
        ...
    
    @property
    def pos(self):
        ...
    
    @pos.setter
    def pos(self, val):
        ...
    


class curve(curveMethods):
    def __init__(self, *args1, **args) -> None:
        ...
    


class points(curveMethods):
    def __init__(self, *args1, **args) -> None:
        ...
    
    @property
    def origin(self):
        ...
    
    @origin.setter
    def origin(self, value):
        ...
    
    @property
    def size_units(self):
        ...
    
    @size_units.setter
    def size_units(self, value): # -> None:
        ...
    
    def rotate(self, **args):
        ...
    


class gobj(baseObj):
    def setup(self, args): # -> None:
        ...
    
    @property
    def visible(self): # -> bool:
        ...
    
    @visible.setter
    def visible(self, val): # -> None:
        ...
    
    @property
    def radius(self): # -> int:
        ...
    
    @radius.setter
    def radius(self, val): # -> None:
        ...
    
    @property
    def size(self): # -> int:
        ...
    
    @size.setter
    def size(self, val): # -> None:
        ...
    
    @property
    def width(self): # -> int:
        ...
    
    @width.setter
    def width(self, val): # -> None:
        ...
    
    @property
    def color(self): # -> vector:
        ...
    
    @color.setter
    def color(self, val): # -> None:
        ...
    
    @property
    def fast(self):
        ...
    
    @fast.setter
    def fast(self, val): # -> None:
        ...
    
    @property
    def graph(self): # -> None:
        ...
    
    @graph.setter
    def graph(self, val): # -> None:
        ...
    
    @property
    def interval(self): # -> int:
        ...
    
    @interval.setter
    def interval(self, val): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def resolveargs(self, *vars): # -> list[Any]:
        ...
    
    def preresolve1(self, *args): # -> list[Any]:
        ...
    
    def preresolve2(self, args): # -> list[Any]:
        ...
    
    def plot(self, *args1, **args2): # -> None:
        ...
    
    def delete(self): # -> None:
        ...
    
    @property
    def label(self): # -> str:
        ...
    
    @label.setter
    def label(self, val): # -> None:
        ...
    
    @property
    def legend(self): # -> bool:
        ...
    
    @legend.setter
    def legend(self, val): # -> None:
        ...
    
    @property
    def data(self): # -> list[Any]:
        ...
    
    @data.setter
    def data(self, val): # -> None:
        ...
    


class gcurve(gobj):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def markers(self):
        ...
    
    @markers.setter
    def markers(self, val): # -> None:
        ...
    
    @property
    def marker_color(self): # -> vector:
        ...
    
    @marker_color.setter
    def marker_color(self, val): # -> None:
        ...
    
    @property
    def dot(self):
        ...
    
    @dot.setter
    def dot(self, val): # -> None:
        ...
    
    @property
    def dot_radius(self):
        ...
    
    @dot_radius.setter
    def dot_radius(self, val): # -> None:
        ...
    
    @property
    def dot_color(self):
        ...
    
    @dot_color.setter
    def dot_color(self, val): # -> None:
        ...
    


class gdots(gobj):
    def __init__(self, **args) -> None:
        ...
    


class gvbars(gobj):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def delta(self): # -> int:
        ...
    
    @delta.setter
    def delta(self, val): # -> None:
        ...
    


class ghbars(gvbars):
    def __init__(self, **args) -> None:
        ...
    


class graph(baseObj):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def fast(self): # -> bool:
        ...
    
    @fast.setter
    def fast(self, val): # -> None:
        ...
    
    @property
    def scroll(self): # -> bool:
        ...
    
    @scroll.setter
    def scroll(self, val): # -> None:
        ...
    
    @property
    def width(self): # -> int:
        ...
    
    @width.setter
    def width(self, val): # -> None:
        ...
    
    @property
    def height(self): # -> int:
        ...
    
    @height.setter
    def height(self, val): # -> None:
        ...
    
    @property
    def align(self): # -> str:
        ...
    
    @align.setter
    def align(self, val): # -> None:
        ...
    
    @property
    def title(self): # -> str:
        ...
    
    @title.setter
    def title(self, val): # -> None:
        ...
    
    @property
    def xtitle(self): # -> str:
        ...
    
    @xtitle.setter
    def xtitle(self, val): # -> None:
        ...
    
    @property
    def ytitle(self): # -> str:
        ...
    
    @ytitle.setter
    def ytitle(self, val): # -> None:
        ...
    
    @property
    def foreground(self): # -> vector:
        ...
    
    @foreground.setter
    def foreground(self, val): # -> None:
        ...
    
    @property
    def background(self): # -> vector:
        ...
    
    @background.setter
    def background(self, val): # -> None:
        ...
    
    @property
    def xmin(self):
        ...
    
    @xmin.setter
    def xmin(self, val): # -> None:
        ...
    
    @property
    def xmax(self):
        ...
    
    @xmax.setter
    def xmax(self, val): # -> None:
        ...
    
    @property
    def ymin(self):
        ...
    
    @ymin.setter
    def ymin(self, val): # -> None:
        ...
    
    @property
    def ymax(self):
        ...
    
    @ymax.setter
    def ymax(self, val): # -> None:
        ...
    
    @property
    def logx(self):
        ...
    
    @logx.setter
    def logx(self, val): # -> None:
        ...
    
    @property
    def logy(self):
        ...
    
    @logx.setter
    def logy(self, val): # -> None:
        ...
    
    def delete(self): # -> None:
        ...
    


class faces:
    def __init__(self, **args) -> None:
        ...
    


class label(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def xoffset(self): # -> int:
        ...
    
    @xoffset.setter
    def xoffset(self, value): # -> None:
        ...
    
    @property
    def yoffset(self): # -> int:
        ...
    
    @yoffset.setter
    def yoffset(self, value): # -> None:
        ...
    
    @property
    def text(self): # -> str:
        ...
    
    @text.setter
    def text(self, value): # -> None:
        ...
    
    @property
    def align(self): # -> None:
        ...
    
    @align.setter
    def align(self, value): # -> None:
        ...
    
    @property
    def font(self): # -> str:
        ...
    
    @font.setter
    def font(self, value): # -> None:
        ...
    
    @property
    def height(self): # -> int:
        ...
    
    @height.setter
    def height(self, value): # -> None:
        ...
    
    @property
    def background(self): # -> None:
        ...
    
    @background.setter
    def background(self, value): # -> None:
        ...
    
    @property
    def border(self): # -> int:
        ...
    
    @border.setter
    def border(self, value): # -> None:
        ...
    
    @property
    def box(self): # -> bool:
        ...
    
    @box.setter
    def box(self, value): # -> None:
        ...
    
    @property
    def line(self): # -> bool:
        ...
    
    @line.setter
    def line(self, value): # -> None:
        ...
    
    @property
    def linewidth(self): # -> int:
        ...
    
    @linewidth.setter
    def linewidth(self, value): # -> None:
        ...
    
    @property
    def linecolor(self): # -> vector | None:
        ...
    
    @linecolor.setter
    def linecolor(self, value): # -> None:
        ...
    
    @property
    def space(self): # -> int:
        ...
    
    @space.setter
    def space(self, value): # -> None:
        ...
    
    @property
    def pixel_pos(self): # -> bool:
        ...
    
    @pixel_pos.setter
    def pixel_pos(self, value): # -> None:
        ...
    


class frame:
    def __init__(self, **args) -> None:
        ...
    


class Mouse(baseObj):
    def __init__(self, canvas) -> None:
        ...
    
    @property
    def pos(self): # -> vector:
        ...
    
    @pos.setter
    def pos(self, value):
        ...
    
    @property
    def ray(self): # -> vector:
        ...
    
    @ray.setter
    def ray(self, value):
        ...
    
    @property
    def ctrl(self): # -> bool:
        ...
    
    @ctrl.setter
    def ctrl(self, value):
        ...
    
    @property
    def shift(self): # -> bool:
        ...
    
    @shift.setter
    def shift(self, value):
        ...
    
    @property
    def alt(self): # -> bool:
        ...
    
    @alt.setter
    def alt(self, value):
        ...
    
    @property
    def pick(self): # -> None:
        ...
    
    @pick.setter
    def pick(self, value):
        ...
    
    def setpick(self, value): # -> None:
        ...
    
    def project(self, **args): # -> None:
        ...
    


class Camera:
    def __init__(self, canvas) -> None:
        ...
    
    @property
    def canvas(self): # -> Any:
        ...
    
    @canvas.setter
    def canvas(self, value):
        ...
    
    @property
    def pos(self):
        ...
    
    @pos.setter
    def pos(self, value): # -> None:
        ...
    
    @property
    def axis(self):
        ...
    
    @axis.setter
    def axis(self, value): # -> None:
        ...
    
    @property
    def up(self):
        ...
    
    @up.setter
    def up(self, value): # -> None:
        ...
    
    def rotate(self, angle=..., axis=..., origin=...): # -> None:
        ...
    


class meta_canvas:
    @property
    def selected(self): # -> Any:
        ...
    
    @selected.setter
    def selected(self, value): # -> None:
        ...
    


class canvas(baseObj):
    selected = ...
    hasmouse = ...
    maxVertices = ...
    def __init__(self, **args) -> None:
        ...
    
    def follow(self, obj): # -> None:
        ...
    
    def select(self): # -> None:
        ...
    
    @classmethod
    def get_selected(cls): # -> Self | None:
        ...
    
    def delete(self): # -> None:
        ...
    
    @property
    def title(self): # -> str:
        ...
    
    @title.setter
    def title(self, value): # -> None:
        ...
    
    @property
    def caption(self): # -> str:
        ...
    
    @caption.setter
    def caption(self, value): # -> None:
        ...
    
    def append_to_title(self, *args): # -> None:
        ...
    
    def append_to_caption(self, *args): # -> None:
        ...
    
    @property
    def mouse(self): # -> Mouse:
        ...
    
    @mouse.setter
    def mouse(self, value):
        ...
    
    @property
    def camera(self): # -> Camera:
        ...
    
    @camera.setter
    def camera(self, value):
        ...
    
    @property
    def visible(self): # -> bool:
        ...
    
    @visible.setter
    def visible(self, value): # -> None:
        ...
    
    @property
    def resizable(self): # -> bool:
        ...
    
    @resizable.setter
    def resizable(self, value): # -> None:
        ...
    
    @property
    def background(self): # -> vector:
        ...
    
    @background.setter
    def background(self, value): # -> None:
        ...
    
    @property
    def ambient(self): # -> vector:
        ...
    
    @ambient.setter
    def ambient(self, value): # -> None:
        ...
    
    @property
    def width(self): # -> int:
        ...
    
    @width.setter
    def width(self, value): # -> None:
        ...
    
    @property
    def height(self): # -> int:
        ...
    
    @height.setter
    def height(self, value): # -> None:
        ...
    
    @property
    def align(self): # -> str:
        ...
    
    @align.setter
    def align(self, val): # -> None:
        ...
    
    @property
    def center(self): # -> vector:
        ...
    
    @center.setter
    def center(self, value): # -> None:
        ...
    
    @property
    def axis(self): # -> vector:
        ...
    
    @axis.setter
    def axis(self, value): # -> None:
        ...
    
    @property
    def forward(self): # -> vector:
        ...
    
    @forward.setter
    def forward(self, value): # -> None:
        ...
    
    @property
    def range(self): # -> int:
        ...
    
    @range.setter
    def range(self, value): # -> None:
        ...
    
    @property
    def up(self): # -> vector:
        ...
    
    @up.setter
    def up(self, value): # -> None:
        ...
    
    @property
    def autoscale(self): # -> bool:
        ...
    
    @autoscale.setter
    def autoscale(self, value): # -> None:
        ...
    
    @property
    def fov(self): # -> float:
        ...
    
    @fov.setter
    def fov(self, value): # -> None:
        ...
    
    @property
    def userzoom(self): # -> bool:
        ...
    
    @userzoom.setter
    def userzoom(self, value): # -> None:
        ...
    
    @property
    def userspin(self): # -> bool:
        ...
    
    @userspin.setter
    def userspin(self, value): # -> None:
        ...
    
    @property
    def userpan(self): # -> bool:
        ...
    
    @userpan.setter
    def userpan(self, value): # -> None:
        ...
    
    @property
    def lights(self): # -> list[Any]:
        ...
    
    @lights.setter
    def lights(self, value): # -> None:
        ...
    
    @property
    def pixel_to_world(self): # -> float:
        ...
    
    @pixel_to_world.setter
    def pixel_to_world(self, value):
        ...
    
    def capture(self, filename, capture_labels=...): # -> None:
        ...
    
    @property
    def objects(self): # -> list[Any]:
        ...
    
    @objects.setter
    def objects(self, *args1, **args):
        ...
    
    def objz(self, obj, operation): # -> None:
        ...
    
    def handle_event(self, evt):
        ...
    
    def bind(self, eventtype, whattodo): # -> None:
        ...
    
    def unbind(self, eventtype, whatnottodo): # -> None:
        ...
    
    def waitfor(self, eventtype): # -> bool | event_return | None:
        ...
    
    def pause(self, *s): # -> bool | event_return:
        ...
    


class event_return:
    def __init__(self, args) -> None:
        ...
    


class local_light(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def offset(self): # -> vector:
        ...
    
    @offset.setter
    def offset(self, value): # -> None:
        ...
    
    @property
    def attach_idx(self): # -> vector:
        ...
    
    @attach_idx.setter
    def attach_idx(self, value): # -> None:
        ...
    


class distant_light(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def direction(self): # -> vector:
        ...
    
    @direction.setter
    def direction(self, value): # -> None:
        ...
    


print_anchor = ...
class wtext(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def text(self): # -> str:
        ...
    
    @text.setter
    def text(self, value): # -> None:
        ...
    


class controls(baseObj):
    attrlists = ...
    def setup(self, args): # -> None:
        ...
    
    @property
    def bind(self):
        ...
    
    @bind.setter
    def bind(self, value):
        ...
    
    @property
    def pos(self):
        ...
    
    @pos.setter
    def pos(self, value):
        ...
    
    @property
    def disabled(self):
        ...
    
    @disabled.setter
    def disabled(self, value): # -> None:
        ...
    
    def delete(self): # -> None:
        ...
    


class button(controls):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def text(self): # -> str:
        ...
    
    @text.setter
    def text(self, value): # -> None:
        ...
    
    @property
    def textcolor(self): # -> vector:
        ...
    
    @textcolor.setter
    def textcolor(self, value): # -> None:
        ...
    
    @property
    def color(self): # -> vector:
        ...
    
    @color.setter
    def color(self, value): # -> None:
        ...
    
    @property
    def background(self): # -> vector:
        ...
    
    @background.setter
    def background(self, value): # -> None:
        ...
    


class checkbox(controls):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def text(self): # -> str:
        ...
    
    @text.setter
    def text(self, value): # -> None:
        ...
    
    @property
    def checked(self): # -> bool:
        ...
    
    @checked.setter
    def checked(self, value): # -> None:
        ...
    


_radio_groups = ...
class radio(controls):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def text(self): # -> str:
        ...
    
    @text.setter
    def text(self, value): # -> None:
        ...
    
    @property
    def checked(self): # -> bool:
        ...
    
    @checked.setter
    def checked(self, value): # -> None:
        ...
    
    @property
    def name(self): # -> str:
        ...
    
    @name.setter
    def name(self, value): # -> None:
        ...
    


class winput(controls):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def text(self): # -> str:
        ...
    
    @text.setter
    def text(self, value): # -> None:
        ...
    
    @property
    def number(self): # -> None:
        ...
    
    @number.setter
    def number(self, value):
        ...
    
    @property
    def width(self): # -> int:
        ...
    
    @width.setter
    def width(self, value):
        ...
    
    @property
    def type(self): # -> str:
        ...
    
    @type.setter
    def type(self, value):
        ...
    


class menu(controls):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def choices(self):
        ...
    
    @choices.setter
    def choices(self, value): # -> None:
        ...
    
    @property
    def index(self): # -> None:
        ...
    
    @index.setter
    def index(self, value): # -> None:
        ...
    
    @property
    def selected(self): # -> str | None:
        ...
    
    @selected.setter
    def selected(self, value): # -> None:
        ...
    


class slider(controls):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def vertical(self): # -> bool:
        ...
    
    @vertical.setter
    def vertical(self, value):
        ...
    
    @property
    def min(self): # -> int:
        ...
    
    @min.setter
    def min(self, value):
        ...
    
    @property
    def max(self): # -> int:
        ...
    
    @max.setter
    def max(self, value):
        ...
    
    @property
    def step(self): # -> float:
        ...
    
    @step.setter
    def step(self, value):
        ...
    
    @property
    def value(self): # -> int:
        ...
    
    @value.setter
    def value(self, val): # -> None:
        ...
    
    @property
    def length(self): # -> int:
        ...
    
    @length.setter
    def length(self, value):
        ...
    
    @property
    def width(self): # -> int:
        ...
    
    @width.setter
    def width(self, value):
        ...
    
    @property
    def left(self): # -> int:
        ...
    
    @left.setter
    def left(self, value):
        ...
    
    @property
    def right(self): # -> int:
        ...
    
    @right.setter
    def right(self, value):
        ...
    
    @property
    def top(self): # -> int:
        ...
    
    @top.setter
    def top(self, value):
        ...
    
    @property
    def bottom(self): # -> int:
        ...
    
    @bottom.setter
    def bottom(self, value):
        ...
    
    @property
    def align(self): # -> str:
        ...
    
    @align.setter
    def align(self, value):
        ...
    


class extrusion(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    def vecs_to_list(self, a, attr): # -> list[float | Any] | list[Any]:
        ...
    
    @property
    def axis(self): # -> vector | NotImplementedType | Any:
        ...
    
    @axis.setter
    def axis(self, value): # -> None:
        ...
    
    @property
    def size(self):
        ...
    
    @size.setter
    def size(self, value): # -> None:
        ...
    
    def level(self, a): # -> Literal[1, 2, 3]:
        ...
    
    def check_shape(self, a): # -> None:
        ...
    
    @property
    def path(self): # -> None:
        ...
    
    @path.setter
    def path(self, value):
        ...
    
    @property
    def shape(self): # -> list[Any] | None:
        ...
    
    @shape.setter
    def shape(self, value):
        ...
    
    @property
    def smooth(self): # -> None:
        ...
    
    @smooth.setter
    def smooth(self, value):
        ...
    
    def checkjointlist(self, js, name): # -> None:
        ...
    
    @property
    def smooth_joints(self): # -> None:
        ...
    
    @smooth_joints.setter
    def smooth_joints(self, value):
        ...
    
    @property
    def sharp_joints(self): # -> None:
        ...
    
    @sharp_joints.setter
    def sharp_joints(self, value):
        ...
    
    @property
    def show_start_face(self): # -> None:
        ...
    
    @show_start_face.setter
    def show_start_face(self, value):
        ...
    
    @property
    def show_end_face(self): # -> None:
        ...
    
    @show_end_face.setter
    def show_end_face(self, value):
        ...
    
    @property
    def start_face_color(self): # -> None:
        ...
    
    @start_face_color.setter
    def start_face_color(self, value):
        ...
    
    @property
    def end_face_color(self): # -> None:
        ...
    
    @end_face_color.setter
    def end_face_color(self, value):
        ...
    
    @property
    def start_normal(self): # -> None:
        ...
    
    @start_normal.setter
    def start_normal(self, value):
        ...
    
    @property
    def end_normal(self): # -> None:
        ...
    
    @end_normal.setter
    def end_normal(self, value):
        ...
    
    @property
    def twist(self): # -> None:
        ...
    
    @twist.setter
    def twist(self, value):
        ...
    
    @property
    def scale(self): # -> None:
        ...
    
    @scale.setter
    def scale(self, value):
        ...
    
    @property
    def xscale(self): # -> None:
        ...
    
    @xscale.setter
    def xscale(self, value):
        ...
    
    @property
    def yscale(self): # -> None:
        ...
    
    @yscale.setter
    def yscale(self, value):
        ...
    
    @property
    def yscale(self): # -> None:
        ...
    
    @yscale.setter
    def yscale(self, value):
        ...
    


class text(standardAttributes):
    def __init__(self, **args) -> None:
        ...
    
    @property
    def size(self):
        ...
    
    @size.setter
    def size(self, val):
        ...
    
    @property
    def axis(self): # -> vector | NotImplementedType | Any:
        ...
    
    @axis.setter
    def axis(self, value): # -> None:
        ...
    
    @property
    def length(self): # -> int:
        ...
    
    @length.setter
    def length(self, val): # -> None:
        ...
    
    @property
    def height(self): # -> int:
        ...
    
    @height.setter
    def height(self, val): # -> None:
        ...
    
    @property
    def depth(self): # -> float:
        ...
    
    @depth.setter
    def depth(self, val): # -> None:
        ...
    
    @property
    def align(self): # -> str:
        ...
    
    @align.setter
    def align(self, val): # -> None:
        ...
    
    @property
    def font(self): # -> str:
        ...
    
    @font.setter
    def font(self, val): # -> None:
        ...
    
    @property
    def text(self): # -> str:
        ...
    
    @text.setter
    def text(self, val): # -> None:
        ...
    
    @property
    def billboard(self): # -> bool:
        ...
    
    @billboard.setter
    def billboard(self, val):
        ...
    
    @property
    def start_face_color(self): # -> vector:
        ...
    
    @start_face_color.setter
    def start_face_color(self, val):
        ...
    
    @property
    def end_face_color(self): # -> vector:
        ...
    
    @end_face_color.setter
    def end_face_color(self, val):
        ...
    
    @property
    def show_start_face(self): # -> bool:
        ...
    
    @show_start_face.setter
    def show_start_face(self, val):
        ...
    
    @property
    def show_end_face(self): # -> bool:
        ...
    
    @show_end_face.setter
    def show_end_face(self, val):
        ...
    
    @property
    def descender(self): # -> float:
        ...
    
    @descender.setter
    def descender(self, val):
        ...
    
    @property
    def upper_left(self): # -> vector | NotImplementedType | Any:
        ...
    
    @upper_left.setter
    def upper_left(self, val):
        ...
    
    @property
    def upper_right(self): # -> vector | NotImplementedType | Any:
        ...
    
    @upper_right.setter
    def upper_right(self, val):
        ...
    
    @property
    def lower_left(self): # -> vector | NotImplementedType | Any:
        ...
    
    @lower_left.setter
    def lower_left(self, val):
        ...
    
    @property
    def lower_right(self): # -> vector | NotImplementedType | Any:
        ...
    
    @lower_right.setter
    def lower_right(self, val):
        ...
    
    @property
    def start(self): # -> vector | NotImplementedType | Any:
        ...
    
    @start.setter
    def start(self, val):
        ...
    
    @property
    def end(self): # -> vector | NotImplementedType | Any:
        ...
    
    @end.setter
    def end(self, val):
        ...
    
    @property
    def vertical_spacing(self): # -> float:
        ...
    
    @vertical_spacing.setter
    def vertical_spacing(self, val):
        ...
    


def combin(x, y): # -> float:
    ...

def sleep(dt): # -> None:
    ...

def print_to_string(*args): # -> str:
    ...

def keysdown(): # -> list[Any]:
    ...

_browsertype = ...
def set_browser(type=...): # -> None:
    ...

